# docker-compose.prod.yml
# AparClic! - Configuración de Producción

version: '3.8'

services:
  client:
    build: 
      context: ./CLIENT
      target: production
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - server
    networks:
      - app-network
    environment:
      - NODE_ENV=production

  server:
    build: ./SERVER
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - DB_URL=${DB_URL}
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGIN=${FRONTEND_URL}
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
